version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - 8888:8888
    networks:
      - laravel-network
    depends_on:
      - db 
  db:
    image: postgres:latest
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravelpassword
      POSTGRES_DB: laravel
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata: